DPAT-2026 Establish project structure and basic tech
ministryofjustice/data-platform-control-panel pull request #3
Opened 2023-11-07 09:53 UTC by ymao2

2023-11-07 15:35 UTC, Gary-H9 commented
Updated devcontainer to include a postgresql , the configuration is in [here](https://github.com/ministryofjustice/data-platform-control-panel/blob/dpat-2062-tech-structure/contrib/docker-compose-postgres.yml). Username and password are configured in there and can be changed if desired. Additionally a [feature](https://github.com/ministryofjustice/data-platform-control-panel/blob/e201cc64dc0093fe422e4b3af2f95c94fc975385/.devcontainer/devcontainer.json#L11) was added to the devcontainer which runs [Docker in Docker](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-in-docker/README.md). From a users perspective this means that `postgresql` is run in a container inside the devcontainer, and you can see the container running on the standard port `5432`. You can connect to the container using the command: 
```
psql -h localhost -U controlpanel
```

2023-11-08 09:38 UTC, michaeljcollinsuk commented
Good starting point 👷‍♀️

2023-11-08 09:38 UTC, michaeljcollinsuk approved these changes

2023-11-08 09:58 UTC, jacobwoffenden requested changes

2023-11-08 09:58 UTC, jacobwoffenden commented on README.md
Can you move `## Running` below the compliance badge?

2023-11-08 10:02 UTC, michaeljcollinsuk commented on README.md
Good catch, done

2023-11-08 13:11 UTC, michaeljcollinsuk submitted a review, later dismissed

2023-11-08 15:39 UTC, michaeljcollinsuk submitted a review, later dismissed

2023-11-08 15:51 UTC, jacobwoffenden approved these changes

2023-11-08 15:52 UTC, michaeljcollinsuk approved these changes

2023-11-08 15:52 UTC, merged